---
# Default theme
oh_my_zsh__theme: robbyrussell

# Default plugins
oh_my_zsh__plugins:
  - git

# Wether to install by default for all specified users.
# May be overridden by `oh_my_zsh__install` under each user.
oh_my_zsh__install: yes
